# Generated by Django 2.0.2 on 2018-02-11 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import focus.apps.accounts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_no', models.CharField(blank=True, max_length=100, null=True)),
                ('date_hired', models.DateField(blank=True, null=True)),
                ('id_no', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('id_file', models.FileField(upload_to=focus.apps.accounts.models.id_location)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(default=('N/A',), max_length=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to=focus.apps.accounts.models.image_location)),
                ('phone_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
