# Generated by Django 2.0.2 on 2018-02-11 15:53

from django.db import migrations, models
import focus.apps.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180211_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id_file',
            field=models.FileField(blank=True, null=True, upload_to=focus.apps.accounts.models.id_location),
        ),
    ]
