# Generated by Django 2.0.2 on 2018-02-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180211_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='tax_pin',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
