# Generated by Django 2.0.2 on 2018-02-11 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import focus.utilities.common


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(default='', max_length=500)),
                ('item', models.FileField(upload_to='files')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=models.SET(focus.utilities.common.get_sentinel_user), related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='approval',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.File'),
        ),
        migrations.AddField(
            model_name='approval',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(focus.utilities.common.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
