# Generated by Django 2.0.2 on 2018-02-11 16:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='approvers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
